namespace AutoDAO.Custom
{
    public class ChavesConfiguracao
    {

        /* Configuração de Backup */
        public static string CHAVE_CONFIGURACAOSERVIDOR_TOKEN = "CHAVE_CONFIGURACAOSERVIDOR_TOKEN";
        public static string CHAVE_CONFIGURACAOSERVIDOR_TEMPO_FECHARCANCELA = "CHAVE_CONFIGURACAOSERVIDOR_TEMPO_FECHARCANCELA";
        public static string CHAVE_CONFIGURACAOSERVIDOR_IP = "CHAVE_CONFIGURACAOSERVIDOR_IP";
        public static string CHAVE_CONFIGURACAOSERVIDOR_PORTA = "CHAVE_CONFIGURACAOSERVIDOR_PORTA";

        /* Contingência */
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_JUSTIFICATIVANFCE = "CHAVE_CONFIGURACAOCONTINGENCIA_JUSTIFICATIVANFCE";
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_DATAHORANFCE = "CHAVE_CONFIGURACAOCONTINGENCIA_DATAHORANFCE";
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_JUSTIFICATIVANFE = "CHAVE_CONFIGURACAOCONTINGENCIA_JUSTIFICATIVANFE";
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_DATAHORANFE = "CHAVE_CONFIGURACAOCONTINGENCIA_DATAHORANFE";
        public static string CHAVE_CONFIGURACAOCONTINGENCIA_TEMPOINTERVALO_MOTOR = "CONFIGURACAOCONTINGENCIA_TEMPOINTERVALO_MOTOR";

        /* Valor P/Hora Estacionamento - Atalhos */
        public static string CHAVE_CONFIGURACAOGERAL_ESTACIONAMENTO = "CHAVE_CONFIGURACAOGERAL_ESTACIONAMENTO";

        /* Login - Lembrar */
        public static string CHAVE_LOGIN_USUARIO_LEMBRAR = "CHAVE_LOGIN_USUARIO_LEMBRAR";

       
    }
}
